### ISSUE TITLE
Issue on page /docs/week_6.html

### ISSUE THREAD

**Issue by thomasbryner** [EPFL-BIO-210/BIO-210-CourseMaterials#12]
The size of the weight matrix for the Storkey rule should be (pattern_size, pattern_size), not (num_patterns, num_patterns). Num_patterns is the number of patterns, whereas we want a matrix of a size equal to the number of neurons which is pattern_size.

**Comment by LucZot** [comment]
Thanks for spotting this error @thomasbryner. We are fixing it :)
